### ISSUE TITLE
Metabase v0.45.1 crashes on Heroku-22 @ OpenJDK 1.8

### ISSUE THREAD

**Issue by holtkamp** [metabase/metabase-buildpack#24]
I am having some problems getting Metabase running (again after Heroku deprecated the free dynos). 

Normally an upgrade could be done like this:
```
git commit --allow-empty -m "empty commit"
git push heroku master
```

This still seems to be the case, since the build succeeds: 
```
-----> Building on the Heroku-22 stack
-----> Using buildpacks:
       1. https://github.com/heroku/heroku-buildpack-jvm-common.git
       2. https://github.com/metabase/metabase-buildpack
-----> JVM Common app detected
-----> Installing OpenJDK 1.8... done
-----> Metabase app detected
-----> Downloading Metabase... from https://downloads.metabase.com/v0.45.1/metabase.jar to /tmp/build_f3f175a6/target/uberjar/metabase.jardone
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 294.5M
-----> Launching...
       Released v44
       https://my-metabase-project.herokuapp.com/ deployed to Heroku
```

But then trying to open the app fails:
```
2022-12-16T15:48:15.000000+00:00 app[api]: Build succeeded
2022-12-16T15:48:25.706758+00:00 heroku[web.1]: Starting process with command `HEROKU=true ./bin/start`
2022-12-16T15:48:26.548927+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2022-12-16T15:48:26.554595+00:00 app[web.1]: -> Heroku detected
2022-12-16T15:48:26.582948+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8
2022-12-16T15:48:28.464410+00:00 app[web.1]: Warning: protocol #'java-time.core/Amount is overwriting function abs
2022-12-16T15:48:28.464766+00:00 app[web.1]: WARNING: abs already refers to: #'clojure.core/abs in namespace: java-time.core, being replaced by: #'java-time.core/abs
2022-12-16T15:48:28.857848+00:00 app[web.1]: WARNING: abs already refers to: #'clojure.core/abs in namespace: java-time, being replaced by: #'java-time/abs
2022-12-16T15:48:29.046916+00:00 app[web.1]: Warning: environ value /app/.jdk for key :java-home has been overwritten with /app/.jdk/jre
2022-12-16T15:48:31.147795+00:00 app[web.1]: 2022-12-16 15:48:31,146 INFO metabase.util :: Maximum memory available to JVM: 300.0 MB
2022-12-16T15:48:32.510589+00:00 app[web.1]: 2022-12-16 15:48:32,510 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
2022-12-16T15:48:32.510627+00:00 app[web.1]: For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2022-12-16T15:48:32.631157+00:00 app[web.1]: WARNING: abs already refers to: #'clojure.core/abs in namespace: taoensso.encore, being replaced by: #'taoensso.encore/abs
2022-12-16T15:48:34.584492+00:00 app[web.1]: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/vladsch/flexmark/ast/HtmlInlineComment has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2022-12-16T15:48:34.584884+00:00 app[web.1]: at java.lang.ClassLoader.defineClass1(Native Method)
2022-12-16T15:48:34.584925+00:00 app[web.1]: at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
2022-12-16T15:48:34.584991+00:00 app[web.1]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2022-12-16T15:48:34.585021+00:00 app[web.1]: at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
2022-12-16T15:48:34.585076+00:00 app[web.1]: at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2022-12-16T15:48:34.585105+00:00 app[web.1]: at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2022-12-16T15:48:34.585129+00:00 app[web.1]: at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2022-12-16T15:48:34.585176+00:00 app[web.1]: at java.security.AccessController.doPrivileged(Native Method)
2022-12-16T15:48:34.585202+00:00 app[web.1]: at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2022-12-16T15:48:34.585229+00:00 app[web.1]: at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
2022-12-16T15:48:34.585259+00:00 app[web.1]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2022-12-16T15:48:34.585287+00:00 app[web.1]: at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
2022-12-16T15:48:34.585314+00:00 app[web.1]: at java.lang.Class.forName0(Native Method)
2022-12-16T15:48:34.585341+00:00 app[web.1]: at java.lang.Class.forName(Class.java:348)
2022-12-16T15:48:34.585369+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2209)
2022-12-16T15:48:34.585399+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2218)
2022-12-16T15:48:34.585441+00:00 app[web.1]: at metabase.pulse.markdown__init.__init0(Unknown Source)
2022-12-16T15:48:34.585457+00:00 app[web.1]: at metabase.pulse.markdown__init.<clinit>(Unknown Source)
2022-12-16T15:48:34.585483+00:00 app[web.1]: at java.lang.Class.forName0(Native Method)
2022-12-16T15:48:34.585511+00:00 app[web.1]: at java.lang.Class.forName(Class.java:348)
2022-12-16T15:48:34.585535+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2209)
2022-12-16T15:48:34.585587+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2218)
2022-12-16T15:48:34.585620+00:00 app[web.1]: at clojure.lang.RT.loadClassForName(RT.java:2237)
2022-12-16T15:48:34.585667+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:449)
2022-12-16T15:48:34.585693+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:424)
2022-12-16T15:48:34.585724+00:00 app[web.1]: at clojure.core$load$fn__6908.invoke(core.clj:6161)
2022-12-16T15:48:34.585752+00:00 app[web.1]: at clojure.core$load.invokeStatic(core.clj:6160)
2022-12-16T15:48:34.585780+00:00 app[web.1]: at clojure.core$load.doInvoke(core.clj:6144)
2022-12-16T15:48:34.585807+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:408)
2022-12-16T15:48:34.585834+00:00 app[web.1]: at clojure.core$load_one.invokeStatic(core.clj:5933)
2022-12-16T15:48:34.585863+00:00 app[web.1]: at clojure.core$load_one.invoke(core.clj:5928)
2022-12-16T15:48:34.585888+00:00 app[web.1]: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
2022-12-16T15:48:34.585915+00:00 app[web.1]: at clojure.core$load_lib.invokeStatic(core.clj:5974)
2022-12-16T15:48:34.585942+00:00 app[web.1]: at clojure.core$load_lib.doInvoke(core.clj:5953)
2022-12-16T15:48:34.585970+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:142)
2022-12-16T15:48:34.586000+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.586054+00:00 app[web.1]: at clojure.core$load_libs.invokeStatic(core.clj:6016)
2022-12-16T15:48:34.586069+00:00 app[web.1]: at clojure.core$load_libs.doInvoke(core.clj:6000)
2022-12-16T15:48:34.586096+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:137)
2022-12-16T15:48:34.586125+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.586153+00:00 app[web.1]: at clojure.core$require.invokeStatic(core.clj:6038)
2022-12-16T15:48:34.586180+00:00 app[web.1]: at clojure.core$require.doInvoke(core.clj:6038)
2022-12-16T15:48:34.586209+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:3894)
2022-12-16T15:48:34.586237+00:00 app[web.1]: at metabase.email.messages$loading__6789__auto____59998.invoke(messages.clj:1)
2022-12-16T15:48:34.586311+00:00 app[web.1]: at metabase.email.messages__init.load(Unknown Source)
2022-12-16T15:48:34.586338+00:00 app[web.1]: at metabase.email.messages__init.<clinit>(Unknown Source)
2022-12-16T15:48:34.586370+00:00 app[web.1]: at java.lang.Class.forName0(Native Method)
2022-12-16T15:48:34.586392+00:00 app[web.1]: at java.lang.Class.forName(Class.java:348)
2022-12-16T15:48:34.586421+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2209)
2022-12-16T15:48:34.586449+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2218)
2022-12-16T15:48:34.586477+00:00 app[web.1]: at clojure.lang.RT.loadClassForName(RT.java:2237)
2022-12-16T15:48:34.586504+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:449)
2022-12-16T15:48:34.586527+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:424)
2022-12-16T15:48:34.586576+00:00 app[web.1]: at clojure.core$load$fn__6908.invoke(core.clj:6161)
2022-12-16T15:48:34.586577+00:00 app[web.1]: at clojure.core$load.invokeStatic(core.clj:6160)
2022-12-16T15:48:34.586604+00:00 app[web.1]: at clojure.core$load.doInvoke(core.clj:6144)
2022-12-16T15:48:34.586630+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:408)
2022-12-16T15:48:34.586671+00:00 app[web.1]: at clojure.core$load_one.invokeStatic(core.clj:5933)
2022-12-16T15:48:34.586706+00:00 app[web.1]: at clojure.core$load_one.invoke(core.clj:5928)
2022-12-16T15:48:34.586736+00:00 app[web.1]: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
2022-12-16T15:48:34.586762+00:00 app[web.1]: at clojure.core$load_lib.invokeStatic(core.clj:5974)
2022-12-16T15:48:34.586790+00:00 app[web.1]: at clojure.core$load_lib.doInvoke(core.clj:5953)
2022-12-16T15:48:34.586869+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:142)
2022-12-16T15:48:34.586935+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.586964+00:00 app[web.1]: at clojure.core$load_libs.invokeStatic(core.clj:6016)
2022-12-16T15:48:34.586988+00:00 app[web.1]: at clojure.core$load_libs.doInvoke(core.clj:6000)
2022-12-16T15:48:34.587015+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:137)
2022-12-16T15:48:34.587042+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.587071+00:00 app[web.1]: at clojure.core$require.invokeStatic(core.clj:6038)
2022-12-16T15:48:34.587095+00:00 app[web.1]: at clojure.core$require.doInvoke(core.clj:6038)
2022-12-16T15:48:34.587123+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:1523)
2022-12-16T15:48:34.587151+00:00 app[web.1]: at metabase.integrations.slack$loading__6789__auto____66705.invoke(slack.clj:1)
2022-12-16T15:48:34.587178+00:00 app[web.1]: at metabase.integrations.slack__init.load(Unknown Source)
2022-12-16T15:48:34.587206+00:00 app[web.1]: at metabase.integrations.slack__init.<clinit>(Unknown Source)
2022-12-16T15:48:34.587233+00:00 app[web.1]: at java.lang.Class.forName0(Native Method)
2022-12-16T15:48:34.587259+00:00 app[web.1]: at java.lang.Class.forName(Class.java:348)
2022-12-16T15:48:34.587287+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2209)
2022-12-16T15:48:34.587316+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2218)
2022-12-16T15:48:34.587367+00:00 app[web.1]: at clojure.lang.RT.loadClassForName(RT.java:2237)
2022-12-16T15:48:34.587394+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:449)
2022-12-16T15:48:34.587422+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:424)
2022-12-16T15:48:34.587477+00:00 app[web.1]: at clojure.core$load$fn__6908.invoke(core.clj:6161)
2022-12-16T15:48:34.587505+00:00 app[web.1]: at clojure.core$load.invokeStatic(core.clj:6160)
2022-12-16T15:48:34.587527+00:00 app[web.1]: at clojure.core$load.doInvoke(core.clj:6144)
2022-12-16T15:48:34.587555+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:408)
2022-12-16T15:48:34.587582+00:00 app[web.1]: at clojure.core$load_one.invokeStatic(core.clj:5933)
2022-12-16T15:48:34.587605+00:00 app[web.1]: at clojure.core$load_one.invoke(core.clj:5928)
2022-12-16T15:48:34.587634+00:00 app[web.1]: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
2022-12-16T15:48:34.587660+00:00 app[web.1]: at clojure.core$load_lib.invokeStatic(core.clj:5974)
2022-12-16T15:48:34.587762+00:00 app[web.1]: at clojure.core$load_lib.doInvoke(core.clj:5953)
2022-12-16T15:48:34.587785+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:142)
2022-12-16T15:48:34.587815+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.587852+00:00 app[web.1]: at clojure.core$load_libs.invokeStatic(core.clj:6016)
2022-12-16T15:48:34.587882+00:00 app[web.1]: at clojure.core$load_libs.doInvoke(core.clj:6000)
2022-12-16T15:48:34.587922+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:137)
2022-12-16T15:48:34.587936+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.587965+00:00 app[web.1]: at clojure.core$require.invokeStatic(core.clj:6038)
2022-12-16T15:48:34.588001+00:00 app[web.1]: at clojure.core$require.doInvoke(core.clj:6038)
2022-12-16T15:48:34.588013+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:2422)
2022-12-16T15:48:34.588046+00:00 app[web.1]: at metabase.analytics.stats$loading__6789__auto____67000.invoke(stats.clj:1)
2022-12-16T15:48:34.588075+00:00 app[web.1]: at metabase.analytics.stats__init.load(Unknown Source)
2022-12-16T15:48:34.588101+00:00 app[web.1]: at metabase.analytics.stats__init.<clinit>(Unknown Source)
2022-12-16T15:48:34.588126+00:00 app[web.1]: at java.lang.Class.forName0(Native Method)
2022-12-16T15:48:34.588155+00:00 app[web.1]: at java.lang.Class.forName(Class.java:348)
2022-12-16T15:48:34.588184+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2209)
2022-12-16T15:48:34.588212+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2218)
2022-12-16T15:48:34.588242+00:00 app[web.1]: at clojure.lang.RT.loadClassForName(RT.java:2237)
2022-12-16T15:48:34.588264+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:449)
2022-12-16T15:48:34.588291+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:424)
2022-12-16T15:48:34.588318+00:00 app[web.1]: at clojure.core$load$fn__6908.invoke(core.clj:6161)
2022-12-16T15:48:34.588345+00:00 app[web.1]: at clojure.core$load.invokeStatic(core.clj:6160)
2022-12-16T15:48:34.588401+00:00 app[web.1]: at clojure.core$load.doInvoke(core.clj:6144)
2022-12-16T15:48:34.588430+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:408)
2022-12-16T15:48:34.588459+00:00 app[web.1]: at clojure.core$load_one.invokeStatic(core.clj:5933)
2022-12-16T15:48:34.588486+00:00 app[web.1]: at clojure.core$load_one.invoke(core.clj:5928)
2022-12-16T15:48:34.588513+00:00 app[web.1]: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
2022-12-16T15:48:34.588540+00:00 app[web.1]: at clojure.core$load_lib.invokeStatic(core.clj:5974)
2022-12-16T15:48:34.588568+00:00 app[web.1]: at clojure.core$load_lib.doInvoke(core.clj:5953)
2022-12-16T15:48:34.588865+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:142)
2022-12-16T15:48:34.588896+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.588938+00:00 app[web.1]: at clojure.core$load_libs.invokeStatic(core.clj:6016)
2022-12-16T15:48:34.588976+00:00 app[web.1]: at clojure.core$load_libs.doInvoke(core.clj:6000)
2022-12-16T15:48:34.589003+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:137)
2022-12-16T15:48:34.589030+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.589109+00:00 app[web.1]: at clojure.core$require.invokeStatic(core.clj:6038)
2022-12-16T15:48:34.589174+00:00 app[web.1]: at clojure.core$require.doInvoke(core.clj:6038)
2022-12-16T15:48:34.589232+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:551)
2022-12-16T15:48:34.589274+00:00 app[web.1]: at metabase.troubleshooting$loading__6789__auto____67243.invoke(troubleshooting.clj:1)
2022-12-16T15:48:34.589300+00:00 app[web.1]: at metabase.troubleshooting__init.load(Unknown Source)
2022-12-16T15:48:34.589325+00:00 app[web.1]: at metabase.troubleshooting__init.<clinit>(Unknown Source)
2022-12-16T15:48:34.589350+00:00 app[web.1]: at java.lang.Class.forName0(Native Method)
2022-12-16T15:48:34.589375+00:00 app[web.1]: at java.lang.Class.forName(Class.java:348)
2022-12-16T15:48:34.589399+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2209)
2022-12-16T15:48:34.589423+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2218)
2022-12-16T15:48:34.589448+00:00 app[web.1]: at clojure.lang.RT.loadClassForName(RT.java:2237)
2022-12-16T15:48:34.589471+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:449)
2022-12-16T15:48:34.589492+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:424)
2022-12-16T15:48:34.589546+00:00 app[web.1]: at clojure.core$load$fn__6908.invoke(core.clj:6161)
2022-12-16T15:48:34.589547+00:00 app[web.1]: at clojure.core$load.invokeStatic(core.clj:6160)
2022-12-16T15:48:34.589578+00:00 app[web.1]: at clojure.core$load.doInvoke(core.clj:6144)
2022-12-16T15:48:34.589605+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:408)
2022-12-16T15:48:34.589628+00:00 app[web.1]: at clojure.core$load_one.invokeStatic(core.clj:5933)
2022-12-16T15:48:34.589651+00:00 app[web.1]: at clojure.core$load_one.invoke(core.clj:5928)
2022-12-16T15:48:34.589674+00:00 app[web.1]: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
2022-12-16T15:48:34.589697+00:00 app[web.1]: at clojure.core$load_lib.invokeStatic(core.clj:5974)
2022-12-16T15:48:34.589720+00:00 app[web.1]: at clojure.core$load_lib.doInvoke(core.clj:5953)
2022-12-16T15:48:34.589742+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:142)
2022-12-16T15:48:34.589765+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.589788+00:00 app[web.1]: at clojure.core$load_libs.invokeStatic(core.clj:6016)
2022-12-16T15:48:34.589810+00:00 app[web.1]: at clojure.core$load_libs.doInvoke(core.clj:6000)
2022-12-16T15:48:34.589833+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:137)
2022-12-16T15:48:34.589855+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.589876+00:00 app[web.1]: at clojure.core$require.invokeStatic(core.clj:6038)
2022-12-16T15:48:34.589897+00:00 app[web.1]: at clojure.core$require.doInvoke(core.clj:6038)
2022-12-16T15:48:34.589920+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:930)
2022-12-16T15:48:34.589944+00:00 app[web.1]: at metabase.analytics.prometheus$loading__6789__auto____82821.invoke(prometheus.clj:1)
2022-12-16T15:48:34.589968+00:00 app[web.1]: at metabase.analytics.prometheus__init.load(Unknown Source)
2022-12-16T15:48:34.590020+00:00 app[web.1]: at metabase.analytics.prometheus__init.<clinit>(Unknown Source)
2022-12-16T15:48:34.590042+00:00 app[web.1]: at java.lang.Class.forName0(Native Method)
2022-12-16T15:48:34.590088+00:00 app[web.1]: at java.lang.Class.forName(Class.java:348)
2022-12-16T15:48:34.590111+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2209)
2022-12-16T15:48:34.590149+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2218)
2022-12-16T15:48:34.590163+00:00 app[web.1]: at clojure.lang.RT.loadClassForName(RT.java:2237)
2022-12-16T15:48:34.590183+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:449)
2022-12-16T15:48:34.590206+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:424)
2022-12-16T15:48:34.590230+00:00 app[web.1]: at clojure.core$load$fn__6908.invoke(core.clj:6161)
2022-12-16T15:48:34.590252+00:00 app[web.1]: at clojure.core$load.invokeStatic(core.clj:6160)
2022-12-16T15:48:34.590274+00:00 app[web.1]: at clojure.core$load.doInvoke(core.clj:6144)
2022-12-16T15:48:34.590296+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:408)
2022-12-16T15:48:34.590319+00:00 app[web.1]: at clojure.core$load_one.invokeStatic(core.clj:5933)
2022-12-16T15:48:34.590342+00:00 app[web.1]: at clojure.core$load_one.invoke(core.clj:5928)
2022-12-16T15:48:34.590364+00:00 app[web.1]: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
2022-12-16T15:48:34.590387+00:00 app[web.1]: at clojure.core$load_lib.invokeStatic(core.clj:5974)
2022-12-16T15:48:34.590410+00:00 app[web.1]: at clojure.core$load_lib.doInvoke(core.clj:5953)
2022-12-16T15:48:34.590452+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:142)
2022-12-16T15:48:34.590472+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.590506+00:00 app[web.1]: at clojure.core$load_libs.invokeStatic(core.clj:6016)
2022-12-16T15:48:34.590539+00:00 app[web.1]: at clojure.core$load_libs.doInvoke(core.clj:6000)
2022-12-16T15:48:34.590563+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:137)
2022-12-16T15:48:34.590586+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.590609+00:00 app[web.1]: at clojure.core$require.invokeStatic(core.clj:6038)
2022-12-16T15:48:34.590630+00:00 app[web.1]: at clojure.core$require.doInvoke(core.clj:6038)
2022-12-16T15:48:34.590653+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:3894)
2022-12-16T15:48:34.590690+00:00 app[web.1]: at metabase.core$loading__6789__auto____87209.invoke(core.clj:1)
2022-12-16T15:48:34.590712+00:00 app[web.1]: at metabase.core__init.load(Unknown Source)
2022-12-16T15:48:34.590786+00:00 app[web.1]: at metabase.core__init.<clinit>(Unknown Source)
2022-12-16T15:48:34.590833+00:00 app[web.1]: at java.lang.Class.forName0(Native Method)
2022-12-16T15:48:34.590855+00:00 app[web.1]: at java.lang.Class.forName(Class.java:348)
2022-12-16T15:48:34.590895+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2209)
2022-12-16T15:48:34.590923+00:00 app[web.1]: at clojure.lang.RT.classForName(RT.java:2218)
2022-12-16T15:48:34.590950+00:00 app[web.1]: at clojure.lang.RT.loadClassForName(RT.java:2237)
2022-12-16T15:48:34.590973+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:449)
2022-12-16T15:48:34.590995+00:00 app[web.1]: at clojure.lang.RT.load(RT.java:424)
2022-12-16T15:48:34.591019+00:00 app[web.1]: at clojure.core$load$fn__6908.invoke(core.clj:6161)
2022-12-16T15:48:34.591049+00:00 app[web.1]: at clojure.core$load.invokeStatic(core.clj:6160)
2022-12-16T15:48:34.591072+00:00 app[web.1]: at clojure.core$load.doInvoke(core.clj:6144)
2022-12-16T15:48:34.591095+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:408)
2022-12-16T15:48:34.591118+00:00 app[web.1]: at clojure.core$load_one.invokeStatic(core.clj:5933)
2022-12-16T15:48:34.591140+00:00 app[web.1]: at clojure.core$load_one.invoke(core.clj:5928)
2022-12-16T15:48:34.591162+00:00 app[web.1]: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
2022-12-16T15:48:34.591185+00:00 app[web.1]: at clojure.core$load_lib.invokeStatic(core.clj:5974)
2022-12-16T15:48:34.591211+00:00 app[web.1]: at clojure.core$load_lib.doInvoke(core.clj:5953)
2022-12-16T15:48:34.591234+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:142)
2022-12-16T15:48:34.591257+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.591280+00:00 app[web.1]: at clojure.core$load_libs.invokeStatic(core.clj:6016)
2022-12-16T15:48:34.591302+00:00 app[web.1]: at clojure.core$load_libs.doInvoke(core.clj:6000)
2022-12-16T15:48:34.591326+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:137)
2022-12-16T15:48:34.591349+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:669)
2022-12-16T15:48:34.591374+00:00 app[web.1]: at clojure.core$require.invokeStatic(core.clj:6038)
2022-12-16T15:48:34.591421+00:00 app[web.1]: at clojure.core$require.doInvoke(core.clj:6038)
2022-12-16T15:48:34.591466+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:137)
2022-12-16T15:48:34.591488+00:00 app[web.1]: at clojure.core$apply.invokeStatic(core.clj:667)
2022-12-16T15:48:34.591512+00:00 app[web.1]: at clojure.core$serialized_require.invokeStatic(core.clj:6114)
2022-12-16T15:48:34.591534+00:00 app[web.1]: at clojure.core$requiring_resolve.invokeStatic(core.clj:6123)
2022-12-16T15:48:34.591574+00:00 app[web.1]: at clojure.core$requiring_resolve.invoke(core.clj:6117)
2022-12-16T15:48:34.591594+00:00 app[web.1]: at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:23)
2022-12-16T15:48:34.591618+00:00 app[web.1]: at metabase.bootstrap$_main.doInvoke(bootstrap.clj:20)
2022-12-16T15:48:34.591640+00:00 app[web.1]: at clojure.lang.RestFn.invoke(RestFn.java:397)
2022-12-16T15:48:34.591664+00:00 app[web.1]: at clojure.lang.AFn.applyToHelper(AFn.java:152)
2022-12-16T15:48:34.591687+00:00 app[web.1]: at clojure.lang.RestFn.applyTo(RestFn.java:132)
2022-12-16T15:48:34.591708+00:00 app[web.1]: at metabase.bootstrap.main(Unknown Source)
2022-12-16T15:48:35.055293+00:00 heroku[web.1]: Process exited with status 1
2022-12-16T15:48:35.098767+00:00 heroku[web.1]: State changed from starting to crashed
```

My Java skills are not very good, but this seems to be the problem: 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/vladsch/flexmark/ast/HtmlInlineComment has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Note that the involved database is running for quite some time already (6 years) and it seems there is a problem loading emails table, at least that is what I derived when going down the stack trace:

```
metabase.email.messages$loading__6789__auto____59998.invoke(messages.clj:1)
```

Any pointer would be welcome!

**Comment by flamber** [comment]
Metabase does not support Java 8 anymore: https://www.metabase.com/docs/latest/installation-and-operation/java-versions

See https://github.com/metabase/metabase-deploy/pull/28

Heroku is being deprecated: https://www.metabase.com/releases/Metabase-0.45#note-that-starting-with-this-release-metabase-045-heroku-support-is-now-deprecated
